version: 0.2.0.{build}
os: Visual Studio 2015
environment:
  NUGETKEY:
    secure: z2fJQckgBQJ7IKfjOyrZYPM2+xDj4xYuqaUDBG7MrJs+b1bNc0vzYMTxpF6Sb1mA
  COVERALLSKEY:
    secure: hVIN9khhDqahcr710lGfodtBvqNxxo9l/vS01Dgk6bcI0r0lr72TMvpDdh3fUAx/
test: off
build_script:
- cmd: build.cmd ci nugetkey=%NUGETKEY% nugetpublishurl=https://www.myget.org/F/saladlab/api/v2/package nugetprerelease=%APPVEYOR_BUILD_NUMBER% coverallskey=%COVERALLSKEY%
