// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Akka.Interfaced CodeGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using Akka.Interfaced;
using Akka.Actor;
using ProtoBuf;
using TypeAlias;
using System.ComponentModel;

#region UnityBasic.Interface.ICalculator

namespace UnityBasic.Interface
{
    [PayloadTable(typeof(ICalculator), PayloadTableKind.Request)]
    public static class ICalculator_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(Concat_Invoke), typeof(Concat_Return) },
                { typeof(Sum_Invoke), typeof(Sum_Return) },
                { typeof(Sum_2_Invoke), typeof(Sum_2_Return) },
            };
        }

        [ProtoContract, TypeAlias]
        public class Concat_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public System.String a;
            [ProtoMember(2)] public System.String b;

            public Type GetInterfaceType()
            {
                return typeof(ICalculator);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((ICalculator)__target).Concat(a, b);
                return (IValueGetable)(new Concat_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class Concat_Return
            : IInterfacedPayload, IValueGetable
        {
            [ProtoMember(1)] public System.String v;

            public Type GetInterfaceType()
            {
                return typeof(ICalculator);
            }

            public object Value
            {
                get { return v; }
            }
        }

        [ProtoContract, TypeAlias]
        public class Sum_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public System.Int32 a;
            [ProtoMember(2)] public System.Int32 b;

            public Type GetInterfaceType()
            {
                return typeof(ICalculator);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((ICalculator)__target).Sum(a, b);
                return (IValueGetable)(new Sum_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class Sum_Return
            : IInterfacedPayload, IValueGetable
        {
            [ProtoMember(1)] public System.Int32 v;

            public Type GetInterfaceType()
            {
                return typeof(ICalculator);
            }

            public object Value
            {
                get { return v; }
            }
        }

        [ProtoContract, TypeAlias]
        public class Sum_2_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public System.Tuple<System.Int32, System.Int32> v;

            public Type GetInterfaceType()
            {
                return typeof(ICalculator);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((ICalculator)__target).Sum(v);
                return (IValueGetable)(new Sum_2_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class Sum_2_Return
            : IInterfacedPayload, IValueGetable
        {
            [ProtoMember(1)] public System.Int32 v;

            public Type GetInterfaceType()
            {
                return typeof(ICalculator);
            }

            public object Value
            {
                get { return v; }
            }
        }
    }

    public interface ICalculator_NoReply
    {
        void Concat(System.String a, System.String b);
        void Sum(System.Int32 a, System.Int32 b);
        void Sum(System.Tuple<System.Int32, System.Int32> v);
    }

    public class CalculatorRef : InterfacedActorRef, ICalculator, ICalculator_NoReply
    {
        public CalculatorRef() : base(null)
        {
        }

        public CalculatorRef(IRequestTarget target) : base(target)
        {
        }

        public CalculatorRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public CalculatorRef(IActorRef actor) : base(new AkkaActorTarget(actor))
        {
        }

        public CalculatorRef(IActorRef actor, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(new AkkaActorTarget(actor), requestWaiter, timeout)
        {
        }

        public IActorRef Actor => ((AkkaActorTarget)Target)?.Actor;

        public ICalculator_NoReply WithNoReply()
        {
            return this;
        }

        public CalculatorRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new CalculatorRef(Target, requestWaiter, Timeout);
        }

        public CalculatorRef WithTimeout(TimeSpan? timeout)
        {
            return new CalculatorRef(Target, RequestWaiter, timeout);
        }

        public Task<System.String> Concat(System.String a, System.String b)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new ICalculator_PayloadTable.Concat_Invoke { a = a, b = b }
            };
            return SendRequestAndReceive<System.String>(requestMessage);
        }

        public Task<System.Int32> Sum(System.Int32 a, System.Int32 b)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new ICalculator_PayloadTable.Sum_Invoke { a = a, b = b }
            };
            return SendRequestAndReceive<System.Int32>(requestMessage);
        }

        public Task<System.Int32> Sum(System.Tuple<System.Int32, System.Int32> v)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new ICalculator_PayloadTable.Sum_2_Invoke { v = v }
            };
            return SendRequestAndReceive<System.Int32>(requestMessage);
        }

        void ICalculator_NoReply.Concat(System.String a, System.String b)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new ICalculator_PayloadTable.Concat_Invoke { a = a, b = b }
            };
            SendRequest(requestMessage);
        }

        void ICalculator_NoReply.Sum(System.Int32 a, System.Int32 b)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new ICalculator_PayloadTable.Sum_Invoke { a = a, b = b }
            };
            SendRequest(requestMessage);
        }

        void ICalculator_NoReply.Sum(System.Tuple<System.Int32, System.Int32> v)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new ICalculator_PayloadTable.Sum_2_Invoke { v = v }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForICalculator
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForICalculator Convert(ICalculator value)
        {
            if (value == null) return null;
            return new SurrogateForICalculator { Target = ((CalculatorRef)value).Target };
        }

        [ProtoConverter]
        public static ICalculator Convert(SurrogateForICalculator value)
        {
            if (value == null) return null;
            return new CalculatorRef(value.Target);
        }
    }

    [AlternativeInterface(typeof(ICalculator))]
    public interface ICalculatorSync : IInterfacedActorSync
    {
        System.String Concat(System.String a, System.String b);
        System.Int32 Sum(System.Int32 a, System.Int32 b);
        System.Int32 Sum(System.Tuple<System.Int32, System.Int32> v);
    }
}

#endregion
#region UnityBasic.Interface.ICounter

namespace UnityBasic.Interface
{
    [PayloadTable(typeof(ICounter), PayloadTableKind.Request)]
    public static class ICounter_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(GetCounter_Invoke), typeof(GetCounter_Return) },
                { typeof(IncCounter_Invoke), null },
            };
        }

        [ProtoContract, TypeAlias]
        public class GetCounter_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Type GetInterfaceType()
            {
                return typeof(ICounter);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((ICounter)__target).GetCounter();
                return (IValueGetable)(new GetCounter_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class GetCounter_Return
            : IInterfacedPayload, IValueGetable
        {
            [ProtoMember(1)] public System.Int32 v;

            public Type GetInterfaceType()
            {
                return typeof(ICounter);
            }

            public object Value
            {
                get { return v; }
            }
        }

        [ProtoContract, TypeAlias]
        public class IncCounter_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public System.Int32 delta;

            public Type GetInterfaceType()
            {
                return typeof(ICounter);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                await ((ICounter)__target).IncCounter(delta);
                return null;
            }
        }
    }

    public interface ICounter_NoReply
    {
        void GetCounter();
        void IncCounter(System.Int32 delta);
    }

    public class CounterRef : InterfacedActorRef, ICounter, ICounter_NoReply
    {
        public CounterRef() : base(null)
        {
        }

        public CounterRef(IRequestTarget target) : base(target)
        {
        }

        public CounterRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public CounterRef(IActorRef actor) : base(new AkkaActorTarget(actor))
        {
        }

        public CounterRef(IActorRef actor, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(new AkkaActorTarget(actor), requestWaiter, timeout)
        {
        }

        public IActorRef Actor => ((AkkaActorTarget)Target)?.Actor;

        public ICounter_NoReply WithNoReply()
        {
            return this;
        }

        public CounterRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new CounterRef(Target, requestWaiter, Timeout);
        }

        public CounterRef WithTimeout(TimeSpan? timeout)
        {
            return new CounterRef(Target, RequestWaiter, timeout);
        }

        public Task<System.Int32> GetCounter()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new ICounter_PayloadTable.GetCounter_Invoke {  }
            };
            return SendRequestAndReceive<System.Int32>(requestMessage);
        }

        public Task IncCounter(System.Int32 delta)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new ICounter_PayloadTable.IncCounter_Invoke { delta = delta }
            };
            return SendRequestAndWait(requestMessage);
        }

        void ICounter_NoReply.GetCounter()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new ICounter_PayloadTable.GetCounter_Invoke {  }
            };
            SendRequest(requestMessage);
        }

        void ICounter_NoReply.IncCounter(System.Int32 delta)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new ICounter_PayloadTable.IncCounter_Invoke { delta = delta }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForICounter
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForICounter Convert(ICounter value)
        {
            if (value == null) return null;
            return new SurrogateForICounter { Target = ((CounterRef)value).Target };
        }

        [ProtoConverter]
        public static ICounter Convert(SurrogateForICounter value)
        {
            if (value == null) return null;
            return new CounterRef(value.Target);
        }
    }

    [AlternativeInterface(typeof(ICounter))]
    public interface ICounterSync : IInterfacedActorSync
    {
        System.Int32 GetCounter();
        void IncCounter(System.Int32 delta);
    }
}

#endregion
#region UnityBasic.Interface.IEntry

namespace UnityBasic.Interface
{
    [PayloadTable(typeof(IEntry), PayloadTableKind.Request)]
    public static class IEntry_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(GetCalculator_Invoke), typeof(GetCalculator_Return) },
                { typeof(GetCounter_Invoke), typeof(GetCounter_Return) },
                { typeof(GetGreeter_Invoke), typeof(GetGreeter_Return) },
                { typeof(GetPedantic_Invoke), typeof(GetPedantic_Return) },
            };
        }

        [ProtoContract, TypeAlias]
        public class GetCalculator_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Type GetInterfaceType()
            {
                return typeof(IEntry);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IEntry)__target).GetCalculator();
                return (IValueGetable)(new GetCalculator_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class GetCalculator_Return
            : IInterfacedPayload, IValueGetable, IPayloadActorRefUpdatable
        {
            [ProtoMember(1)] public UnityBasic.Interface.ICalculator v;

            public Type GetInterfaceType()
            {
                return typeof(IEntry);
            }

            public object Value
            {
                get { return v; }
            }

            void IPayloadActorRefUpdatable.Update(Action<object> updater)
            {
                if (v != null)
                {
                    updater(v); 
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class GetCounter_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Type GetInterfaceType()
            {
                return typeof(IEntry);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IEntry)__target).GetCounter();
                return (IValueGetable)(new GetCounter_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class GetCounter_Return
            : IInterfacedPayload, IValueGetable, IPayloadActorRefUpdatable
        {
            [ProtoMember(1)] public UnityBasic.Interface.ICounter v;

            public Type GetInterfaceType()
            {
                return typeof(IEntry);
            }

            public object Value
            {
                get { return v; }
            }

            void IPayloadActorRefUpdatable.Update(Action<object> updater)
            {
                if (v != null)
                {
                    updater(v); 
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class GetGreeter_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Type GetInterfaceType()
            {
                return typeof(IEntry);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IEntry)__target).GetGreeter();
                return (IValueGetable)(new GetGreeter_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class GetGreeter_Return
            : IInterfacedPayload, IValueGetable, IPayloadActorRefUpdatable
        {
            [ProtoMember(1)] public UnityBasic.Interface.IGreeterWithObserver v;

            public Type GetInterfaceType()
            {
                return typeof(IEntry);
            }

            public object Value
            {
                get { return v; }
            }

            void IPayloadActorRefUpdatable.Update(Action<object> updater)
            {
                if (v != null)
                {
                    updater(v); 
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class GetPedantic_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Type GetInterfaceType()
            {
                return typeof(IEntry);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IEntry)__target).GetPedantic();
                return (IValueGetable)(new GetPedantic_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class GetPedantic_Return
            : IInterfacedPayload, IValueGetable, IPayloadActorRefUpdatable
        {
            [ProtoMember(1)] public UnityBasic.Interface.IPedantic v;

            public Type GetInterfaceType()
            {
                return typeof(IEntry);
            }

            public object Value
            {
                get { return v; }
            }

            void IPayloadActorRefUpdatable.Update(Action<object> updater)
            {
                if (v != null)
                {
                    updater(v); 
                }
            }
        }
    }

    public interface IEntry_NoReply
    {
        void GetCalculator();
        void GetCounter();
        void GetGreeter();
        void GetPedantic();
    }

    public class EntryRef : InterfacedActorRef, IEntry, IEntry_NoReply
    {
        public EntryRef() : base(null)
        {
        }

        public EntryRef(IRequestTarget target) : base(target)
        {
        }

        public EntryRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public EntryRef(IActorRef actor) : base(new AkkaActorTarget(actor))
        {
        }

        public EntryRef(IActorRef actor, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(new AkkaActorTarget(actor), requestWaiter, timeout)
        {
        }

        public IActorRef Actor => ((AkkaActorTarget)Target)?.Actor;

        public IEntry_NoReply WithNoReply()
        {
            return this;
        }

        public EntryRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new EntryRef(Target, requestWaiter, Timeout);
        }

        public EntryRef WithTimeout(TimeSpan? timeout)
        {
            return new EntryRef(Target, RequestWaiter, timeout);
        }

        public Task<UnityBasic.Interface.ICalculator> GetCalculator()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IEntry_PayloadTable.GetCalculator_Invoke {  }
            };
            return SendRequestAndReceive<UnityBasic.Interface.ICalculator>(requestMessage);
        }

        public Task<UnityBasic.Interface.ICounter> GetCounter()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IEntry_PayloadTable.GetCounter_Invoke {  }
            };
            return SendRequestAndReceive<UnityBasic.Interface.ICounter>(requestMessage);
        }

        public Task<UnityBasic.Interface.IGreeterWithObserver> GetGreeter()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IEntry_PayloadTable.GetGreeter_Invoke {  }
            };
            return SendRequestAndReceive<UnityBasic.Interface.IGreeterWithObserver>(requestMessage);
        }

        public Task<UnityBasic.Interface.IPedantic> GetPedantic()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IEntry_PayloadTable.GetPedantic_Invoke {  }
            };
            return SendRequestAndReceive<UnityBasic.Interface.IPedantic>(requestMessage);
        }

        void IEntry_NoReply.GetCalculator()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IEntry_PayloadTable.GetCalculator_Invoke {  }
            };
            SendRequest(requestMessage);
        }

        void IEntry_NoReply.GetCounter()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IEntry_PayloadTable.GetCounter_Invoke {  }
            };
            SendRequest(requestMessage);
        }

        void IEntry_NoReply.GetGreeter()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IEntry_PayloadTable.GetGreeter_Invoke {  }
            };
            SendRequest(requestMessage);
        }

        void IEntry_NoReply.GetPedantic()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IEntry_PayloadTable.GetPedantic_Invoke {  }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForIEntry
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForIEntry Convert(IEntry value)
        {
            if (value == null) return null;
            return new SurrogateForIEntry { Target = ((EntryRef)value).Target };
        }

        [ProtoConverter]
        public static IEntry Convert(SurrogateForIEntry value)
        {
            if (value == null) return null;
            return new EntryRef(value.Target);
        }
    }

    [AlternativeInterface(typeof(IEntry))]
    public interface IEntrySync : IInterfacedActorSync
    {
        UnityBasic.Interface.ICalculator GetCalculator();
        UnityBasic.Interface.ICounter GetCounter();
        UnityBasic.Interface.IGreeterWithObserver GetGreeter();
        UnityBasic.Interface.IPedantic GetPedantic();
    }
}

#endregion
#region UnityBasic.Interface.IGreeter

namespace UnityBasic.Interface
{
    [PayloadTable(typeof(IGreeter), PayloadTableKind.Request)]
    public static class IGreeter_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(GetCount_Invoke), typeof(GetCount_Return) },
                { typeof(Greet_Invoke), typeof(Greet_Return) },
            };
        }

        [ProtoContract, TypeAlias]
        public class GetCount_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Type GetInterfaceType()
            {
                return typeof(IGreeter);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IGreeter)__target).GetCount();
                return (IValueGetable)(new GetCount_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class GetCount_Return
            : IInterfacedPayload, IValueGetable
        {
            [ProtoMember(1)] public System.Int32 v;

            public Type GetInterfaceType()
            {
                return typeof(IGreeter);
            }

            public object Value
            {
                get { return v; }
            }
        }

        [ProtoContract, TypeAlias]
        public class Greet_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public System.String name;

            public Type GetInterfaceType()
            {
                return typeof(IGreeter);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IGreeter)__target).Greet(name);
                return (IValueGetable)(new Greet_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class Greet_Return
            : IInterfacedPayload, IValueGetable
        {
            [ProtoMember(1)] public System.String v;

            public Type GetInterfaceType()
            {
                return typeof(IGreeter);
            }

            public object Value
            {
                get { return v; }
            }
        }
    }

    public interface IGreeter_NoReply
    {
        void GetCount();
        void Greet(System.String name);
    }

    public class GreeterRef : InterfacedActorRef, IGreeter, IGreeter_NoReply
    {
        public GreeterRef() : base(null)
        {
        }

        public GreeterRef(IRequestTarget target) : base(target)
        {
        }

        public GreeterRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public GreeterRef(IActorRef actor) : base(new AkkaActorTarget(actor))
        {
        }

        public GreeterRef(IActorRef actor, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(new AkkaActorTarget(actor), requestWaiter, timeout)
        {
        }

        public IActorRef Actor => ((AkkaActorTarget)Target)?.Actor;

        public IGreeter_NoReply WithNoReply()
        {
            return this;
        }

        public GreeterRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new GreeterRef(Target, requestWaiter, Timeout);
        }

        public GreeterRef WithTimeout(TimeSpan? timeout)
        {
            return new GreeterRef(Target, RequestWaiter, timeout);
        }

        public Task<System.Int32> GetCount()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGreeter_PayloadTable.GetCount_Invoke {  }
            };
            return SendRequestAndReceive<System.Int32>(requestMessage);
        }

        public Task<System.String> Greet(System.String name)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGreeter_PayloadTable.Greet_Invoke { name = name }
            };
            return SendRequestAndReceive<System.String>(requestMessage);
        }

        void IGreeter_NoReply.GetCount()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGreeter_PayloadTable.GetCount_Invoke {  }
            };
            SendRequest(requestMessage);
        }

        void IGreeter_NoReply.Greet(System.String name)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGreeter_PayloadTable.Greet_Invoke { name = name }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForIGreeter
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForIGreeter Convert(IGreeter value)
        {
            if (value == null) return null;
            return new SurrogateForIGreeter { Target = ((GreeterRef)value).Target };
        }

        [ProtoConverter]
        public static IGreeter Convert(SurrogateForIGreeter value)
        {
            if (value == null) return null;
            return new GreeterRef(value.Target);
        }
    }

    [AlternativeInterface(typeof(IGreeter))]
    public interface IGreeterSync : IInterfacedActorSync
    {
        System.Int32 GetCount();
        System.String Greet(System.String name);
    }
}

#endregion
#region UnityBasic.Interface.IGreeterWithObserver

namespace UnityBasic.Interface
{
    [PayloadTable(typeof(IGreeterWithObserver), PayloadTableKind.Request)]
    public static class IGreeterWithObserver_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(Subscribe_Invoke), null },
                { typeof(Unsubscribe_Invoke), null },
            };
        }

        [ProtoContract, TypeAlias]
        public class Subscribe_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadObserverUpdatable
        {
            [ProtoMember(1)] public UnityBasic.Interface.IGreetObserver observer;

            public Type GetInterfaceType()
            {
                return typeof(IGreeterWithObserver);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                await ((IGreeterWithObserver)__target).Subscribe(observer);
                return null;
            }

            void IPayloadObserverUpdatable.Update(Action<IInterfacedObserver> updater)
            {
                if (observer != null)
                {
                    updater(observer);
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class Unsubscribe_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadObserverUpdatable
        {
            [ProtoMember(1)] public UnityBasic.Interface.IGreetObserver observer;

            public Type GetInterfaceType()
            {
                return typeof(IGreeterWithObserver);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                await ((IGreeterWithObserver)__target).Unsubscribe(observer);
                return null;
            }

            void IPayloadObserverUpdatable.Update(Action<IInterfacedObserver> updater)
            {
                if (observer != null)
                {
                    updater(observer);
                }
            }
        }
    }

    public interface IGreeterWithObserver_NoReply : IGreeter_NoReply
    {
        void Subscribe(UnityBasic.Interface.IGreetObserver observer);
        void Unsubscribe(UnityBasic.Interface.IGreetObserver observer);
    }

    public class GreeterWithObserverRef : InterfacedActorRef, IGreeterWithObserver, IGreeterWithObserver_NoReply
    {
        public GreeterWithObserverRef() : base(null)
        {
        }

        public GreeterWithObserverRef(IRequestTarget target) : base(target)
        {
        }

        public GreeterWithObserverRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public GreeterWithObserverRef(IActorRef actor) : base(new AkkaActorTarget(actor))
        {
        }

        public GreeterWithObserverRef(IActorRef actor, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(new AkkaActorTarget(actor), requestWaiter, timeout)
        {
        }

        public IActorRef Actor => ((AkkaActorTarget)Target)?.Actor;

        public IGreeterWithObserver_NoReply WithNoReply()
        {
            return this;
        }

        public GreeterWithObserverRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new GreeterWithObserverRef(Target, requestWaiter, Timeout);
        }

        public GreeterWithObserverRef WithTimeout(TimeSpan? timeout)
        {
            return new GreeterWithObserverRef(Target, RequestWaiter, timeout);
        }

        public Task Subscribe(UnityBasic.Interface.IGreetObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGreeterWithObserver_PayloadTable.Subscribe_Invoke { observer = (GreetObserver)observer }
            };
            return SendRequestAndWait(requestMessage);
        }

        public Task Unsubscribe(UnityBasic.Interface.IGreetObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGreeterWithObserver_PayloadTable.Unsubscribe_Invoke { observer = (GreetObserver)observer }
            };
            return SendRequestAndWait(requestMessage);
        }

        public Task<System.Int32> GetCount()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGreeter_PayloadTable.GetCount_Invoke {  }
            };
            return SendRequestAndReceive<System.Int32>(requestMessage);
        }

        public Task<System.String> Greet(System.String name)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGreeter_PayloadTable.Greet_Invoke { name = name }
            };
            return SendRequestAndReceive<System.String>(requestMessage);
        }

        void IGreeterWithObserver_NoReply.Subscribe(UnityBasic.Interface.IGreetObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGreeterWithObserver_PayloadTable.Subscribe_Invoke { observer = (GreetObserver)observer }
            };
            SendRequest(requestMessage);
        }

        void IGreeterWithObserver_NoReply.Unsubscribe(UnityBasic.Interface.IGreetObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGreeterWithObserver_PayloadTable.Unsubscribe_Invoke { observer = (GreetObserver)observer }
            };
            SendRequest(requestMessage);
        }

        void IGreeter_NoReply.GetCount()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGreeter_PayloadTable.GetCount_Invoke {  }
            };
            SendRequest(requestMessage);
        }

        void IGreeter_NoReply.Greet(System.String name)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGreeter_PayloadTable.Greet_Invoke { name = name }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForIGreeterWithObserver
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForIGreeterWithObserver Convert(IGreeterWithObserver value)
        {
            if (value == null) return null;
            return new SurrogateForIGreeterWithObserver { Target = ((GreeterWithObserverRef)value).Target };
        }

        [ProtoConverter]
        public static IGreeterWithObserver Convert(SurrogateForIGreeterWithObserver value)
        {
            if (value == null) return null;
            return new GreeterWithObserverRef(value.Target);
        }
    }

    [AlternativeInterface(typeof(IGreeterWithObserver))]
    public interface IGreeterWithObserverSync : IGreeterSync
    {
        void Subscribe(UnityBasic.Interface.IGreetObserver observer);
        void Unsubscribe(UnityBasic.Interface.IGreetObserver observer);
    }
}

#endregion
#region UnityBasic.Interface.IPedantic

namespace UnityBasic.Interface
{
    [PayloadTable(typeof(IPedantic), PayloadTableKind.Request)]
    public static class IPedantic_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(TestCall_Invoke), null },
                { typeof(TestOptional_Invoke), typeof(TestOptional_Return) },
                { typeof(TestParams_Invoke), typeof(TestParams_Return) },
                { typeof(TestPassClass_Invoke), typeof(TestPassClass_Return) },
                { typeof(TestReturnClass_Invoke), typeof(TestReturnClass_Return) },
                { typeof(TestTuple_Invoke), typeof(TestTuple_Return) },
            };
        }

        [ProtoContract, TypeAlias]
        public class TestCall_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Type GetInterfaceType()
            {
                return typeof(IPedantic);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                await ((IPedantic)__target).TestCall();
                return null;
            }
        }

        [ProtoContract, TypeAlias]
        public class TestOptional_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public System.Nullable<System.Int32> value;

            public Type GetInterfaceType()
            {
                return typeof(IPedantic);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IPedantic)__target).TestOptional(value);
                return (IValueGetable)(new TestOptional_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class TestOptional_Return
            : IInterfacedPayload, IValueGetable
        {
            [ProtoMember(1)] public System.Nullable<System.Int32> v;

            public Type GetInterfaceType()
            {
                return typeof(IPedantic);
            }

            public object Value
            {
                get { return v; }
            }
        }

        [ProtoContract, TypeAlias]
        public class TestParams_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public System.Int32[] values;

            public Type GetInterfaceType()
            {
                return typeof(IPedantic);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IPedantic)__target).TestParams(values);
                return (IValueGetable)(new TestParams_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class TestParams_Return
            : IInterfacedPayload, IValueGetable
        {
            [ProtoMember(1)] public System.Int32[] v;

            public Type GetInterfaceType()
            {
                return typeof(IPedantic);
            }

            public object Value
            {
                get { return v; }
            }
        }

        [ProtoContract, TypeAlias]
        public class TestPassClass_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public UnityBasic.Interface.TestParam param;

            public Type GetInterfaceType()
            {
                return typeof(IPedantic);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IPedantic)__target).TestPassClass(param);
                return (IValueGetable)(new TestPassClass_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class TestPassClass_Return
            : IInterfacedPayload, IValueGetable
        {
            [ProtoMember(1)] public System.String v;

            public Type GetInterfaceType()
            {
                return typeof(IPedantic);
            }

            public object Value
            {
                get { return v; }
            }
        }

        [ProtoContract, TypeAlias]
        public class TestReturnClass_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public System.Int32 value;
            [ProtoMember(2)] public System.Int32 offset;

            public Type GetInterfaceType()
            {
                return typeof(IPedantic);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IPedantic)__target).TestReturnClass(value, offset);
                return (IValueGetable)(new TestReturnClass_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class TestReturnClass_Return
            : IInterfacedPayload, IValueGetable
        {
            [ProtoMember(1)] public UnityBasic.Interface.TestResult v;

            public Type GetInterfaceType()
            {
                return typeof(IPedantic);
            }

            public object Value
            {
                get { return v; }
            }
        }

        [ProtoContract, TypeAlias]
        public class TestTuple_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public System.Tuple<System.Int32, System.String> value;

            public Type GetInterfaceType()
            {
                return typeof(IPedantic);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IPedantic)__target).TestTuple(value);
                return (IValueGetable)(new TestTuple_Return { v = __v });
            }
        }

        [ProtoContract, TypeAlias]
        public class TestTuple_Return
            : IInterfacedPayload, IValueGetable
        {
            [ProtoMember(1)] public System.Tuple<System.Int32, System.String> v;

            public Type GetInterfaceType()
            {
                return typeof(IPedantic);
            }

            public object Value
            {
                get { return v; }
            }
        }
    }

    public interface IPedantic_NoReply
    {
        void TestCall();
        void TestOptional(System.Nullable<System.Int32> value);
        void TestParams(params System.Int32[] values);
        void TestPassClass(UnityBasic.Interface.TestParam param);
        void TestReturnClass(System.Int32 value, System.Int32 offset);
        void TestTuple(System.Tuple<System.Int32, System.String> value);
    }

    public class PedanticRef : InterfacedActorRef, IPedantic, IPedantic_NoReply
    {
        public PedanticRef() : base(null)
        {
        }

        public PedanticRef(IRequestTarget target) : base(target)
        {
        }

        public PedanticRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public PedanticRef(IActorRef actor) : base(new AkkaActorTarget(actor))
        {
        }

        public PedanticRef(IActorRef actor, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(new AkkaActorTarget(actor), requestWaiter, timeout)
        {
        }

        public IActorRef Actor => ((AkkaActorTarget)Target)?.Actor;

        public IPedantic_NoReply WithNoReply()
        {
            return this;
        }

        public PedanticRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new PedanticRef(Target, requestWaiter, Timeout);
        }

        public PedanticRef WithTimeout(TimeSpan? timeout)
        {
            return new PedanticRef(Target, RequestWaiter, timeout);
        }

        public Task TestCall()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IPedantic_PayloadTable.TestCall_Invoke {  }
            };
            return SendRequestAndWait(requestMessage);
        }

        public Task<System.Nullable<System.Int32>> TestOptional(System.Nullable<System.Int32> value)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IPedantic_PayloadTable.TestOptional_Invoke { value = value }
            };
            return SendRequestAndReceive<System.Nullable<System.Int32>>(requestMessage);
        }

        public Task<System.Int32[]> TestParams(params System.Int32[] values)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IPedantic_PayloadTable.TestParams_Invoke { values = values }
            };
            return SendRequestAndReceive<System.Int32[]>(requestMessage);
        }

        public Task<System.String> TestPassClass(UnityBasic.Interface.TestParam param)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IPedantic_PayloadTable.TestPassClass_Invoke { param = param }
            };
            return SendRequestAndReceive<System.String>(requestMessage);
        }

        public Task<UnityBasic.Interface.TestResult> TestReturnClass(System.Int32 value, System.Int32 offset)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IPedantic_PayloadTable.TestReturnClass_Invoke { value = value, offset = offset }
            };
            return SendRequestAndReceive<UnityBasic.Interface.TestResult>(requestMessage);
        }

        public Task<System.Tuple<System.Int32, System.String>> TestTuple(System.Tuple<System.Int32, System.String> value)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IPedantic_PayloadTable.TestTuple_Invoke { value = value }
            };
            return SendRequestAndReceive<System.Tuple<System.Int32, System.String>>(requestMessage);
        }

        void IPedantic_NoReply.TestCall()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IPedantic_PayloadTable.TestCall_Invoke {  }
            };
            SendRequest(requestMessage);
        }

        void IPedantic_NoReply.TestOptional(System.Nullable<System.Int32> value)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IPedantic_PayloadTable.TestOptional_Invoke { value = value }
            };
            SendRequest(requestMessage);
        }

        void IPedantic_NoReply.TestParams(params System.Int32[] values)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IPedantic_PayloadTable.TestParams_Invoke { values = values }
            };
            SendRequest(requestMessage);
        }

        void IPedantic_NoReply.TestPassClass(UnityBasic.Interface.TestParam param)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IPedantic_PayloadTable.TestPassClass_Invoke { param = param }
            };
            SendRequest(requestMessage);
        }

        void IPedantic_NoReply.TestReturnClass(System.Int32 value, System.Int32 offset)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IPedantic_PayloadTable.TestReturnClass_Invoke { value = value, offset = offset }
            };
            SendRequest(requestMessage);
        }

        void IPedantic_NoReply.TestTuple(System.Tuple<System.Int32, System.String> value)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IPedantic_PayloadTable.TestTuple_Invoke { value = value }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForIPedantic
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForIPedantic Convert(IPedantic value)
        {
            if (value == null) return null;
            return new SurrogateForIPedantic { Target = ((PedanticRef)value).Target };
        }

        [ProtoConverter]
        public static IPedantic Convert(SurrogateForIPedantic value)
        {
            if (value == null) return null;
            return new PedanticRef(value.Target);
        }
    }

    [AlternativeInterface(typeof(IPedantic))]
    public interface IPedanticSync : IInterfacedActorSync
    {
        void TestCall();
        System.Nullable<System.Int32> TestOptional(System.Nullable<System.Int32> value);
        System.Int32[] TestParams(params System.Int32[] values);
        System.String TestPassClass(UnityBasic.Interface.TestParam param);
        UnityBasic.Interface.TestResult TestReturnClass(System.Int32 value, System.Int32 offset);
        System.Tuple<System.Int32, System.String> TestTuple(System.Tuple<System.Int32, System.String> value);
    }
}

#endregion
#region UnityBasic.Interface.IGreetObserver

namespace UnityBasic.Interface
{
    [PayloadTable(typeof(IGreetObserver), PayloadTableKind.Notification)]
    public static class IGreetObserver_PayloadTable
    {
        public static Type[] GetPayloadTypes()
        {
            return new Type[] {
                typeof(Event_Invoke),
            };
        }

        [ProtoContract, TypeAlias]
        public class Event_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public System.String message;

            public Type GetInterfaceType()
            {
                return typeof(IGreetObserver);
            }

            public void Invoke(object __target)
            {
                ((IGreetObserver)__target).Event(message);
            }
        }
    }

    public class GreetObserver : InterfacedObserver, IGreetObserver
    {
        public GreetObserver()
            : base(null, 0)
        {
        }

        public GreetObserver(INotificationChannel channel, int observerId = 0)
            : base(channel, observerId)
        {
        }

        public void Event(System.String message)
        {
            var payload = new IGreetObserver_PayloadTable.Event_Invoke { message = message };
            Notify(payload);
        }
    }

    [ProtoContract]
    public class SurrogateForIGreetObserver
    {
        [ProtoMember(1)] public INotificationChannel Channel;
        [ProtoMember(2)] public int ObserverId;

        [ProtoConverter]
        public static SurrogateForIGreetObserver Convert(IGreetObserver value)
        {
            if (value == null) return null;
            var o = (GreetObserver)value;
            return new SurrogateForIGreetObserver { Channel = o.Channel, ObserverId = o.ObserverId };
        }

        [ProtoConverter]
        public static IGreetObserver Convert(SurrogateForIGreetObserver value)
        {
            if (value == null) return null;
            return new GreetObserver(value.Channel, value.ObserverId);
        }
    }

    [AlternativeInterface(typeof(IGreetObserver))]
    public interface IGreetObserverAsync : IInterfacedObserverSync
    {
        Task Event(System.String message);
    }
}

#endregion
